// ============================================
// POCKETCLASS — Mock Data for MVP
// ============================================

import { Instructor, Course, LiveSession, Conversation, Message, PlatformStats, Review } from '@/types';

// ---------- Instructors ----------
export const instructors: Instructor[] = [
  {
    id: 'inst-1',
    name: 'Sarah Chen',
    email: 'sarah@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Full-stack developer with 10+ years of experience. Passionate about teaching web development, React, and modern JavaScript patterns.',
    expertise: ['Web Development', 'React', 'TypeScript', 'Node.js'],
    rating: 4.9,
    reviewCount: 342,
    studentCount: 2840,
    courseCount: 8,
    hourlyRate: 75,
    createdAt: '2024-01-15',
    socialLinks: { linkedin: '#', twitter: '#', website: '#' },
  },
  {
    id: 'inst-2',
    name: 'Marcus Johnson',
    email: 'marcus@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    bio: 'Professional game designer and Unity expert. Teaching game development from concept to deployment for over 7 years.',
    expertise: ['Game Development', 'Unity', 'C#', '3D Modeling'],
    rating: 4.8,
    reviewCount: 198,
    studentCount: 1560,
    courseCount: 5,
    hourlyRate: 85,
    createdAt: '2024-02-20',
    socialLinks: { linkedin: '#', twitter: '#' },
  },
  {
    id: 'inst-3',
    name: 'Emily Rodriguez',
    email: 'emily@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    bio: 'UX/UI design lead at a Fortune 500 company. Specializing in design systems, Figma, and user research methodologies.',
    expertise: ['UI/UX Design', 'Figma', 'Design Systems', 'User Research'],
    rating: 4.95,
    reviewCount: 276,
    studentCount: 2100,
    courseCount: 6,
    hourlyRate: 90,
    createdAt: '2024-03-10',
    socialLinks: { linkedin: '#', website: '#' },
  },
  {
    id: 'inst-4',
    name: 'David Kim',
    email: 'david@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    bio: 'Data scientist and AI researcher. Making machine learning accessible to everyone through hands-on projects and clear explanations.',
    expertise: ['Machine Learning', 'Python', 'Data Science', 'TensorFlow'],
    rating: 4.85,
    reviewCount: 420,
    studentCount: 3200,
    courseCount: 10,
    hourlyRate: 95,
    createdAt: '2024-01-05',
    socialLinks: { linkedin: '#', twitter: '#', website: '#' },
  },
  {
    id: 'inst-5',
    name: 'Lisa Thompson',
    email: 'lisa@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    bio: 'Professional photographer and videographer. Teaching creative skills from beginner to pro level with real-world projects.',
    expertise: ['Photography', 'Video Editing', 'Adobe Suite', 'Content Creation'],
    rating: 4.7,
    reviewCount: 156,
    studentCount: 890,
    courseCount: 4,
    hourlyRate: 60,
    createdAt: '2024-04-01',
    socialLinks: { twitter: '#', website: '#' },
  },
  {
    id: 'inst-6',
    name: 'Alex Rivera',
    email: 'alex@pocketclass.com',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Cybersecurity expert and ethical hacker. Helping professionals and organizations stay safe in the digital world.',
    expertise: ['Cybersecurity', 'Ethical Hacking', 'Network Security', 'Linux'],
    rating: 4.88,
    reviewCount: 310,
    studentCount: 1750,
    courseCount: 7,
    hourlyRate: 100,
    createdAt: '2024-02-14',
    socialLinks: { linkedin: '#' },
  },
];

// ---------- Courses ----------
export const courses: Course[] = [
  {
    id: 'course-1',
    title: 'Complete React & TypeScript Masterclass 2025',
    slug: 'react-typescript-masterclass',
    description: 'Master React and TypeScript from the ground up. Build production-ready applications with modern best practices, state management, testing, and deployment strategies.',
    shortDescription: 'Build production-ready React apps with TypeScript',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[0],
    price: 79.99,
    originalPrice: 129.99,
    category: 'Web Development',
    tags: ['React', 'TypeScript', 'Frontend'],
    level: 'intermediate',
    rating: 4.9,
    reviewCount: 342,
    studentCount: 2840,
    duration: '42 hours',
    lessonCount: 156,
    isFeatured: true,
    isPublished: true,
    createdAt: '2024-06-15',
    updatedAt: '2025-01-10',
    chapters: [
      {
        id: 'ch-1-1', title: 'Getting Started with React & TypeScript', order: 1,
        lessons: [
          { id: 'l-1', title: 'Course Overview & Setup', type: 'video', duration: '12:30', order: 1, isFree: true },
          { id: 'l-2', title: 'TypeScript Fundamentals', type: 'video', duration: '28:15', order: 2 },
          { id: 'l-3', title: 'Your First React Component', type: 'video', duration: '22:40', order: 3 },
          { id: 'l-4', title: 'Props and State with Types', type: 'video', duration: '35:20', order: 4 },
        ],
      },
      {
        id: 'ch-1-2', title: 'Advanced Patterns', order: 2,
        lessons: [
          { id: 'l-5', title: 'Custom Hooks Deep Dive', type: 'video', duration: '41:00', order: 1 },
          { id: 'l-6', title: 'Context API & State Management', type: 'video', duration: '38:15', order: 2 },
          { id: 'l-7', title: 'Performance Optimization', type: 'video', duration: '29:50', order: 3 },
        ],
      },
      {
        id: 'ch-1-3', title: 'Building Real Projects', order: 3,
        lessons: [
          { id: 'l-8', title: 'Project: Task Manager App', type: 'video', duration: '55:00', order: 1 },
          { id: 'l-9', title: 'Project: E-commerce Dashboard', type: 'video', duration: '1:02:30', order: 2 },
          { id: 'l-10', title: 'Deployment & CI/CD', type: 'video', duration: '24:15', order: 3 },
        ],
      },
    ],
  },
  {
    id: 'course-2',
    title: 'Game Development with Unity: From Zero to Hero',
    slug: 'unity-game-dev',
    description: 'Learn to build complete games using Unity. From basic mechanics to advanced AI systems, multiplayer, and publishing your game.',
    shortDescription: 'Create professional games with Unity & C#',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[1],
    price: 89.99,
    originalPrice: 149.99,
    category: 'Game Development',
    tags: ['Unity', 'C#', 'Game Design'],
    level: 'beginner',
    rating: 4.8,
    reviewCount: 198,
    studentCount: 1560,
    duration: '38 hours',
    lessonCount: 120,
    isFeatured: true,
    isPublished: true,
    createdAt: '2024-07-01',
    updatedAt: '2025-02-01',
    chapters: [
      {
        id: 'ch-2-1', title: 'Unity Fundamentals', order: 1,
        lessons: [
          { id: 'l-11', title: 'Installing Unity & First Project', type: 'video', duration: '15:00', order: 1, isFree: true },
          { id: 'l-12', title: 'Understanding the Unity Editor', type: 'video', duration: '25:30', order: 2 },
          { id: 'l-13', title: 'GameObjects and Components', type: 'video', duration: '30:00', order: 3 },
        ],
      },
      {
        id: 'ch-2-2', title: '2D Game Development', order: 2,
        lessons: [
          { id: 'l-14', title: 'Sprite Animation', type: 'video', duration: '35:20', order: 1 },
          { id: 'l-15', title: 'Physics & Collisions', type: 'video', duration: '28:45', order: 2 },
          { id: 'l-16', title: 'Building a Platformer', type: 'video', duration: '48:00', order: 3 },
        ],
      },
    ],
  },
  {
    id: 'course-3',
    title: 'UI/UX Design: Complete Design System Bootcamp',
    slug: 'uiux-design-bootcamp',
    description: 'Master the art of UI/UX design. Learn design thinking, build design systems in Figma, conduct user research, and create stunning interfaces.',
    shortDescription: 'Master UI/UX design with real-world projects',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[2],
    price: 69.99,
    category: 'Design',
    tags: ['UI/UX', 'Figma', 'Design Systems'],
    level: 'beginner',
    rating: 4.95,
    reviewCount: 276,
    studentCount: 2100,
    duration: '30 hours',
    lessonCount: 98,
    isFeatured: true,
    isPublished: true,
    createdAt: '2024-08-10',
    updatedAt: '2025-01-20',
    chapters: [
      {
        id: 'ch-3-1', title: 'Design Fundamentals', order: 1,
        lessons: [
          { id: 'l-17', title: 'Design Principles & Theory', type: 'video', duration: '20:00', order: 1, isFree: true },
          { id: 'l-18', title: 'Color Theory in Practice', type: 'video', duration: '32:15', order: 2 },
          { id: 'l-19', title: 'Typography Mastery', type: 'video', duration: '27:40', order: 3 },
        ],
      },
      {
        id: 'ch-3-2', title: 'Figma Deep Dive', order: 2,
        lessons: [
          { id: 'l-20', title: 'Figma Interface & Tools', type: 'video', duration: '25:00', order: 1 },
          { id: 'l-21', title: 'Auto Layout & Constraints', type: 'video', duration: '38:30', order: 2 },
          { id: 'l-22', title: 'Building Component Libraries', type: 'video', duration: '45:15', order: 3 },
        ],
      },
    ],
  },
  {
    id: 'course-4',
    title: 'Machine Learning A-Z: From Basics to Production',
    slug: 'ml-basics-to-production',
    description: 'Comprehensive machine learning course covering supervised learning, deep learning, NLP, computer vision, and deploying ML models to production.',
    shortDescription: 'Learn ML from theory to real-world deployment',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[3],
    price: 99.99,
    originalPrice: 179.99,
    category: 'Data Science',
    tags: ['Machine Learning', 'Python', 'AI'],
    level: 'intermediate',
    rating: 4.85,
    reviewCount: 420,
    studentCount: 3200,
    duration: '52 hours',
    lessonCount: 185,
    isFeatured: true,
    isPublished: true,
    createdAt: '2024-05-20',
    updatedAt: '2025-02-15',
    chapters: [
      {
        id: 'ch-4-1', title: 'ML Foundations', order: 1,
        lessons: [
          { id: 'l-23', title: 'What is Machine Learning?', type: 'video', duration: '18:00', order: 1, isFree: true },
          { id: 'l-24', title: 'Python for ML: NumPy & Pandas', type: 'video', duration: '42:30', order: 2 },
          { id: 'l-25', title: 'Linear Regression from Scratch', type: 'video', duration: '35:20', order: 3 },
        ],
      },
    ],
  },
  {
    id: 'course-5',
    title: 'Photography Masterclass: From Beginner to Pro',
    slug: 'photography-masterclass',
    description: 'Learn professional photography techniques. Master composition, lighting, editing, and building your portfolio.',
    shortDescription: 'Capture stunning photos like a professional',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[4],
    price: 49.99,
    category: 'Photography',
    tags: ['Photography', 'Lightroom', 'Composition'],
    level: 'beginner',
    rating: 4.7,
    reviewCount: 156,
    studentCount: 890,
    duration: '24 hours',
    lessonCount: 78,
    isPublished: true,
    createdAt: '2024-09-01',
    updatedAt: '2025-01-05',
    chapters: [
      {
        id: 'ch-5-1', title: 'Camera Basics', order: 1,
        lessons: [
          { id: 'l-26', title: 'Understanding Your Camera', type: 'video', duration: '22:00', order: 1, isFree: true },
          { id: 'l-27', title: 'Aperture, Shutter, ISO', type: 'video', duration: '30:15', order: 2 },
        ],
      },
    ],
  },
  {
    id: 'course-6',
    title: 'Ethical Hacking & Cybersecurity Fundamentals',
    slug: 'ethical-hacking-fundamentals',
    description: 'Learn cybersecurity and ethical hacking. Conduct penetration tests, find vulnerabilities, and protect networks.',
    shortDescription: 'Master cybersecurity and ethical hacking',
    thumbnail: '/api/placeholder/800/450',
    instructor: instructors[5],
    price: 84.99,
    originalPrice: 139.99,
    category: 'Cybersecurity',
    tags: ['Hacking', 'Security', 'Linux'],
    level: 'intermediate',
    rating: 4.88,
    reviewCount: 310,
    studentCount: 1750,
    duration: '35 hours',
    lessonCount: 130,
    isPublished: true,
    createdAt: '2024-06-25',
    updatedAt: '2025-02-10',
    chapters: [
      {
        id: 'ch-6-1', title: 'Security Foundations', order: 1,
        lessons: [
          { id: 'l-28', title: 'Intro to Cybersecurity', type: 'video', duration: '16:00', order: 1, isFree: true },
          { id: 'l-29', title: 'Linux for Hackers', type: 'video', duration: '40:30', order: 2 },
        ],
      },
    ],
  },
];

// ---------- Live Sessions ----------
export const liveSessions: LiveSession[] = [
  {
    id: 'session-1',
    title: 'Live React Code Review & Q&A',
    description: 'Bring your React projects for a live code review. Get personalized feedback on architecture, performance, and best practices.',
    instructor: instructors[0],
    date: '2025-04-02',
    time: '2:00 PM',
    duration: '90 min',
    timezone: 'EST',
    price: 29.99,
    maxParticipants: 30,
    enrolledCount: 22,
    status: 'upcoming',
    category: 'Web Development',
  },
  {
    id: 'session-2',
    title: 'Unity Workshop: Build a Mobile Game',
    description: 'Hands-on workshop where we build a complete mobile game in Unity from scratch. Follow along and ship your first mobile game.',
    instructor: instructors[1],
    date: '2025-04-05',
    time: '10:00 AM',
    duration: '2 hours',
    timezone: 'EST',
    price: 39.99,
    maxParticipants: 25,
    enrolledCount: 18,
    status: 'upcoming',
    category: 'Game Development',
  },
  {
    id: 'session-3',
    title: 'Design Critique: Portfolio Review',
    description: 'Submit your design portfolio for a live critique session. Get actionable feedback from an industry leader.',
    instructor: instructors[2],
    date: '2025-04-08',
    time: '3:00 PM',
    duration: '60 min',
    timezone: 'EST',
    price: 24.99,
    maxParticipants: 20,
    enrolledCount: 15,
    status: 'upcoming',
    category: 'Design',
  },
  {
    id: 'session-4',
    title: 'ML Office Hours: Model Debugging',
    description: 'Struggling with model accuracy? Join this open office hours session for personalized debugging help.',
    instructor: instructors[3],
    date: '2025-04-10',
    time: '1:00 PM',
    duration: '90 min',
    timezone: 'EST',
    price: 34.99,
    maxParticipants: 15,
    enrolledCount: 12,
    status: 'upcoming',
    category: 'Data Science',
  },
];

// ---------- Reviews ----------
export const reviews: Review[] = [
  { id: 'r-1', courseId: 'course-1', studentId: 's-1', studentName: 'James W.', studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', rating: 5, comment: 'Best React course I have ever taken. Sarah explains complex concepts in a way that just clicks. The projects are incredibly practical.', createdAt: '2025-01-15' },
  { id: 'r-2', courseId: 'course-1', studentId: 's-2', studentName: 'Maria L.', studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria', rating: 5, comment: 'Went from struggling with TypeScript to feeling confident building full-stack apps. Absolutely worth every penny.', createdAt: '2025-01-20' },
  { id: 'r-3', courseId: 'course-1', studentId: 's-3', studentName: 'Tom B.', studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom', rating: 4, comment: 'Great content and well-structured. A few lessons could be more in-depth, but overall an excellent course.', createdAt: '2025-02-01' },
  { id: 'r-4', courseId: 'course-2', studentId: 's-4', studentName: 'Sophie K.', studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie', rating: 5, comment: 'I built my first game from scratch thanks to this course. Marcus is an amazing teacher!', createdAt: '2025-01-25' },
  { id: 'r-5', courseId: 'course-3', studentId: 's-5', studentName: 'Ryan P.', studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan', rating: 5, comment: 'Emily\'s design course transformed how I approach UI work. The design system module alone is worth the price.', createdAt: '2025-02-05' },
];

// ---------- Conversations (Messages) ----------
export const mockMessages: Message[] = [
  { id: 'm-1', senderId: 'student-1', receiverId: 'inst-1', content: 'Hi Sarah! I had a question about the custom hooks lesson.', timestamp: '2025-03-20T10:30:00', isRead: true },
  { id: 'm-2', senderId: 'inst-1', receiverId: 'student-1', content: 'Of course! What part are you having trouble with?', timestamp: '2025-03-20T10:35:00', isRead: true },
  { id: 'm-3', senderId: 'student-1', receiverId: 'inst-1', content: 'I am confused about when to use useCallback vs useMemo. Could you clarify?', timestamp: '2025-03-20T10:38:00', isRead: true },
  { id: 'm-4', senderId: 'inst-1', receiverId: 'student-1', content: 'Great question! useCallback memoizes the function itself, while useMemo memoizes the return value. I cover this in lesson 7 — let me know if that helps!', timestamp: '2025-03-20T10:42:00', isRead: false },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: [
      { id: 'student-1', name: 'You', email: '', role: 'student', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Student', createdAt: '' },
      instructors[0],
    ],
    lastMessage: mockMessages[3],
    unreadCount: 1,
  },
  {
    id: 'conv-2',
    participants: [
      { id: 'student-1', name: 'You', email: '', role: 'student', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Student', createdAt: '' },
      instructors[2],
    ],
    lastMessage: { id: 'm-5', senderId: 'inst-3', receiverId: 'student-1', content: 'Your portfolio redesign looks great! Just a few tweaks on the color palette.', timestamp: '2025-03-19T14:20:00', isRead: true },
    unreadCount: 0,
  },
];

// ---------- Platform Stats (Admin) ----------
export const platformStats: PlatformStats = {
  totalUsers: 12450,
  totalInstructors: 148,
  totalStudents: 12302,
  totalCourses: 456,
  totalRevenue: 892350,
  activeSessionsToday: 12,
  newUsersThisMonth: 1240,
  revenueThisMonth: 67890,
};

// ---------- Categories ----------
export const categories = [
  { name: 'Web Development', icon: '💻', count: 124 },
  { name: 'Game Development', icon: '🎮', count: 56 },
  { name: 'Design', icon: '🎨', count: 89 },
  { name: 'Data Science', icon: '📊', count: 72 },
  { name: 'Photography', icon: '📷', count: 45 },
  { name: 'Cybersecurity', icon: '🔒', count: 38 },
  { name: 'Business', icon: '💼', count: 67 },
  { name: 'Music', icon: '🎵', count: 34 },
];
